### ISSUE TITLE
Add a metric_description property / attribute to BaseMetric

### ISSUE THREAD

**Issue by AlstonLin** [asottile/git-code-debt#74]
It would be nice to have an easy way to store what each metric is actually measuring that can be displayed to users when metric_name might not be descriptive enough.

**Comment by asottile** [comment]
I wonder if we can use `__doc__` (a docstring) for this.  I have another piece of related/similar software that uses a markdown `__doc__` with pretty good success.

**Comment by asottile** [comment]
Oh right, I remember why this is difficult -- `Metric`s can be omitted one->many, that is a single `DiffParserBase` can make many `Metric`s with different names.

In order to handle something like this we'd have to change the table creation.  In the current scheme it's probably ok to have one description map to many different metrics?  Most of the metrics (except for the code lines ones) are 1:1 already.

If you want to start hacking, this is where I'd start looking :) https://github.com/asottile/git-code-debt/blob/master/git_code_debt/create_tables.py

**Comment by asottile** [comment]
I think what I want to happen here is the [`get_possible_metric_ids`](https://github.com/asottile/git-code-debt/blob/ef203ca0c6081298db19c8130d6a2206214c116c/git_code_debt/metrics/base.py#L25-L26) should be refactored into something like `get_metric_info`

For simple metrics it could be implemented something like:

```python
def get_metric_info(self):
    return [MetricInfo(type(self).__name__, description=type(self).__doc__)]
```

This could then get parsed with [markdown-code-blocks](https://github.com/asottile/markdown-code-blocks) and displayed on the graph page

For backwards compatibility, `get_metric_info` can have a default implementation of:

```python
def get_metric_info(self):
    return [MetricInfo(name) for name in self.get_possible_metric_ids()]
```

thoughts?
