### ISSUE TITLE
Support for multiple repos

### ISSUE THREAD

**Issue by theresama** [asottile/git-code-debt#97]
Consider adding support for multiple repos?

**Comment by asottile** [comment]
This was actually part of the initial version but pulled out due to complexity.

The current suggestion is to run an instance per repository.  @chriskuehl threw together [chriskuehl/codedebt.io](https://github.com/chriskuehl/codedebt.io) as a sort of automatic-generator app -- maybe something to consider?

I guess stepping back: what's the usecase for multiple repositories -- how would the UI look for that and what would you want to get out of it?
